---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  enable_yum_epel: true
#  name: chef_solo
  sudo_command: 'sudo -E -H'

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
## https://bugs.launchpad.net/ubuntu/+source/sysdig/+bug/1419402 (fixed)
  - name: ubuntu-14.04
## Not available
#  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.7
#  - name: bento/centos-6.7

suites:
  - name: default
    run_list:
    attributes:
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/default-capture.yml

