---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
## only default defined ansible repo is for ubuntu
## https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md
  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
#  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
#  ansible_yum_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm     ## failing???
#  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm       ## no ansible package
  enable_yum_epel: true
#  name: chef_solo

platforms:
## https://bugs.launchpad.net/ubuntu/+source/sysdig/+bug/1419402
#  - name: ubuntu-14.04
## Not available
#  - name: ubuntu-12.04
  - name: centos-7.1
  - name: bento/centos-6.7

suites:
  - name: default
    run_list:
    attributes:

