---

- name: Import unix-mkdir
  ansible.builtin.import_tasks: unix-mkdir.yml

- name: Import debian
  ansible.builtin.import_tasks: debian.yml
  when: >
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and
    (sysdig_install is defined and sysdig_install)

- name: Import redhat
  ansible.builtin.import_tasks: redhat.yml
  when: >
    (ansible_os_family == "RedHat") and
    (sysdig_install is defined and sysdig_install)

- name: Import sysdig
  ansible.builtin.import_tasks: sysdig.yml
  when: ansible_system == 'Linux' and sysdig_capture is defined and sysdig_capture
  tags:
    - system
    - sysdig
