---

- name: Redhat | install draios repository key
  ansible.builtin.rpm_key:
    state: present
    key: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
- name: Redhat | install draios repository
  ansible.builtin.get_url:
    url: http://download.draios.com/stable/rpm/draios.repo
    dest: /etc/yum.repos.d/draios.repo
    mode: 0644

- name: Redhat | sysdig install
  ansible.builtin.dnf:
    name:
      - dkms
      - kernel-devel
      # - "kernel-devel-{{ ansible_kernel }}"
      - sysdig
    state: present
    update_cache: yes
