---

- name: ensure sysdig kernel module loaded
  modprobe: name=sysdig-probe state=present
  ignore_errors: true

- stat: path={{ dst_path }}/{{ prefix }}-sysdig.scap
  register: scap

- name: Sysdig capture
## this commit is still not in package...
#  shell: "sysdig -G {{ capture_length }} -w {{ dst_path }}/{{ prefix }}-sysdig.scap"
  shell: "sysdig -n {{ capture_numevent }} -w {{ dst_path }}/{{ prefix }}-sysdig.scap"
  when: not scap.stat.exists

