---

- name: ensure sysdig kernel module loaded
  modprobe: name=sysdig-probe state=present
  ignore_errors: true

- name: Sysdig capture - length
  ansible.builtin.command: "sysdig -M {{ sysdig_capture_length }} -w {{ sysdig_capturefile }}"
  args:
    creates: "{{ sysdig_capturefile }}"
  when: sysdig_capture_length is defined
- name: Sysdig capture - numevents
  ansible.builtin.command: "sysdig -n {{ sysdig_capture_numevent }} -w {{ sysdig_capturefile }}"
  args:
    creates: "{{ sysdig_capturefile }}"
  when: sysdig_capture_length is not defined
