---

- name: ensure sysdig kernel module loaded
  modprobe: name=sysdig-probe state=present
  ignore_errors: true

- stat: path={{ sysdig_capturefile }}
  register: scap

- name: Sysdig capture
## this commit is still not in package...
#  shell: "sysdig -G {{ capture_length }} -w {{ dst_path }}/{{ prefix }}-sysdig.scap"
  shell: "sysdig -n {{ sysdig_capture_numevent }} -w {{ sysdig_capturefile }}"
  when: not scap.stat.exists

