---

## if those path are mounted network directory, the command will fail (existing or not)
- name: Ensure dst_mount directory exists
  ansible.builtin.file:
    path: "{{ dst_mount }}"
    state: directory
    mode: '0755'
  failed_when: false
# - name: Ensure bin_path directory exists
#   ansible.builtin.file:
#     path: "{{ bin_path }}"
#     state: directory
#     mode: '0755'
#   failed_when: false

- name: Ensure dst_path directory exists
  ansible.builtin.file:
    path: "{{ dst_path }}"
    state: directory
    mode: '0755'
